theme: jekyll-theme-minimal
title: Alex Nastas
description: Network Engineer, Cloud architect, Business Development
address: Frankfurt Area, Germany
linkedin: https://www.linkedin.com/in/alexnastas/
email: alex.nastas@gmail.com
resume_pdf_url: resume_alexnastas_feb2022.pdf